### ISSUE TITLE
Error while using GPU

### ISSUE THREAD

**Issue by Mars160** [seasonjs/stable-diffusion#2]
I have a NVIDIA 4090 and an Intel GPU on my machine. I want to load model to my 4090. However, it only checked my intel gpu and said it's now support.

How to use my NVIDIA GPU not the Intel One?

Thank you.

**Comment by Mars160** [comment]
I try to load the library manually, but it said `The specified module could not be found.` (sd-abi_cuda12.dll)

When I try to load sd-abi_avx2.dll, It works.

**Comment by Cyberhan123** [comment]
@Mars160  Can you run the following command in powershell
```
Get-WmiObject Win32_VideoController | Format-List Name,AdapterCompatibility,AdapterRAM
```

**Comment by Mars160** [comment]
Thanks for your reply.

And here is the output

```plaintext
Name                 : Virtual Desktop Monitor
AdapterCompatibility : Virtual Desktop, Inc.
AdapterRAM           :

Name                 : NVIDIA GeForce RTX 4090
AdapterCompatibility : NVIDIA
AdapterRAM           : 4293918720

Name                 : Virtual Display
AdapterCompatibility : Xiaomi
AdapterRAM           :

Name                 : Intel(R) UHD Graphics 770
AdapterCompatibility : Intel Corporation
AdapterRAM           : 1073741824
```

**Comment by Mars160** [comment]
Thanks for your hard work! The GPU selection issue was fixed!

However, there is another issue. I can load 'sd-abi_cuda12.dll'

```plaintext
2024/01/10 13:55:31 get gpu info: NVIDIA GeForce RTX 4090
2024/01/10 13:55:31 Use GPU CUDA instead.
2024/01/10 13:55:31 If you want to try offload your model to the GPU. Please confirm the size of your GPU memory to prevent memory overflow.
The specified module could not be found.
```

And I found we should blame it on golang's package. I tried 

```golang
package main

import "syscall"

func main() {
	lib, err := syscall.LoadLibrary("sd-abi_cuda12.dll")
	if err != nil {
		panic(err)
	}
	defer syscall.FreeLibrary(lib)
}
```

I got
```plaintext
panic: The specified module could not be found.

goroutine 1 [running]:
main.main()
        C:/other/AI/sd-go/test.go:8 +0x79
exit status 2
```

When I change the library from `sd-abi_cuda12.dll` to `sd-abi_avx2.dll`, It loaded it successfully.

I'm not so familiar to stable diffusion library. Is there a way to fix this?

Thank you!

**Comment by Cyberhan123** [comment]
@Mars160  Have you installed cuda?

**Comment by Mars160** [comment]
Thank you! You solved my problem perfectly!
